fos_user:
  db_driver: orm
  firewall_name: main
  user_class: App\Entity\User
  registration:
    form:
      type: App\Form\RegistrationType
  from_email:
    address: "raphaelreboullet@gmail.com"
    sender_name: "raphaelreboullet@gmail.com"